# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-23 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptype', '0004_auto_20160713_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextend',
            name='dob',
        ),
        migrations.AddField(
            model_name='userextend',
            name='eng_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextend',
            name='nep_speed',
            field=models.IntegerField(default=0),
        ),
    ]
