# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-25 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neptype', '0005_auto_20160723_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='verified',
            field=models.IntegerField(default=0),
        ),
    ]
